# Generated by Django 4.1.7 on 2023-04-23 21:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Only letters and spaces are allowed.')])),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Only 10 digits are allowed.')])),
                ('city', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator("^[a-zA-Z0-9 ,.\\'-]*$", 'Only letters, numbers, spaces, commas, periods, apostrophes and hyphens are allowed.')])),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0, 'Age cannot be negative.')])),
                ('company', models.TextField()),
                ('summary', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'], 'Only jpg, jpeg, png and gif files are allowed.')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
