# Generated by Django 4.1.7 on 2023-05-03 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Recruiters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('application_link', models.URLField()),
                ('company_name', models.CharField(max_length=100)),
                ('salary', models.PositiveIntegerField()),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
