# Generated by Django 4.1.7 on 2023-05-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiters', '0002_joblisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='salary',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
