# Generated by Django 4.1.7 on 2023-05-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiters', '0006_alter_joblisting_recruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='job_type',
            field=models.CharField(choices=[('FT', 'Full-time'), ('PT', 'Part-time'), ('ST', 'Student'), ('IN', 'Intern')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
