# Generated by Django 4.1.7 on 2023-05-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiters', '0007_joblisting_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='job_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Student', 'Student'), ('Intern', 'Intern')], max_length=20),
        ),
    ]
