# Generated by Django 4.1.7 on 2023-05-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiters', '0008_alter_joblisting_job_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('resume', models.FileField(upload_to='resumes/')),
            ],
        ),
    ]
