# Generated by Django 4.1.7 on 2023-05-20 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiters', '0009_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Recruiters.joblisting'),
            preserve_default=False,
        ),
    ]
