# Generated by Django 4.1.7 on 2023-05-20 09:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiters', '0010_interest_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='media', validators=[django.core.validators.FileExtensionValidator(['pdf'], 'Only pdf files are allowed.')]),
        ),
    ]
