# Generated by Django 4.1.7 on 2023-05-20 09:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiters', '0011_alter_interest_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Only PDF files are allowed.')]),
        ),
    ]
