# Generated by Django 4.1.7 on 2023-05-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiters', '0012_alter_interest_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='status',
            field=models.CharField(choices=[('in_process', 'In Process'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('qualified', 'Qualified'), ('awaiting_decision', 'Awaiting Decision'), ('new_applicant', 'New Applicant')], default='new Applicant', max_length=20),
        ),
    ]
