# Generated by Django 4.2.1 on 2023-06-04 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiters', '0013_interest_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
