# Generated by Django 4.1.7 on 2023-04-15 17:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juniors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juniors',
            name='cv_file',
            field=models.FileField(upload_to='media', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='juniors',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'])]),
        ),
    ]
