# Generated by Django 4.1.7 on 2023-04-15 18:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juniors', '0002_alter_juniors_cv_file_alter_juniors_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juniors',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10), django.core.validators.validate_integer]),
        ),
    ]
