# Generated by Django 4.1.7 on 2023-04-15 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juniors', '0003_alter_juniors_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juniors',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10), django.core.validators.RegexValidator(message='Phone number must be 10 digits.', regex='^\\d{10}$')]),
        ),
    ]
