# Generated by Django 4.1.7 on 2023-04-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juniors', '0004_alter_juniors_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juniors',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
