# Generated by Django 4.1.7 on 2023-04-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juniors', '0005_alter_juniors_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juniors',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='juniors',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='juniors',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='juniors',
            name='skills',
            field=models.TextField(),
        ),
    ]
