# Generated by Django 4.1.7 on 2023-04-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juniors', '0006_alter_juniors_age_alter_juniors_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juniors',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
