# Generated by Django 4.1.7 on 2023-04-16 08:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juniors', '0007_alter_juniors_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juniors',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0, 'Age cannot be negative.')]),
        ),
        migrations.AlterField(
            model_name='juniors',
            name='city',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator("^[a-zA-Z0-9 ,.\\'-]*$", 'Only letters, numbers, spaces, commas, periods, apostrophes and hyphens are allowed.')]),
        ),
        migrations.AlterField(
            model_name='juniors',
            name='cv_file',
            field=models.FileField(upload_to='media', validators=[django.core.validators.FileExtensionValidator(['pdf'], 'Only pdf files are allowed.')]),
        ),
        migrations.AlterField(
            model_name='juniors',
            name='full_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Only letters and spaces are allowed.')]),
        ),
        migrations.AlterField(
            model_name='juniors',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Only 10 digits are allowed.')]),
        ),
        migrations.AlterField(
            model_name='juniors',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'], 'Only jpg, jpeg, png and gif files are allowed.')]),
        ),
        migrations.AlterField(
            model_name='juniors',
            name='skills',
            field=models.TextField(validators=[django.core.validators.RegexValidator("^[a-zA-Z ,.\\'-]*$", 'Only letters, spaces, commas, periods, apostrophes and hyphens are allowed.')]),
        ),
    ]
