# Generated by Django 4.2.1 on 2023-06-04 12:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiters', '0014_delete_interest'),
        ('Juniors', '0013_juniors_generated_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Only PDF files are allowed.')])),
                ('status', models.CharField(choices=[('in_process', 'In Process'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('qualified', 'Qualified'), ('awaiting_decision', 'Awaiting Decision'), ('new_applicant', 'New Applicant')], default='new Applicant', max_length=20)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recruiters.joblisting')),
                ('junior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Juniors.juniors')),
            ],
        ),
        migrations.AddField(
            model_name='juniors',
            name='applied_jobs',
            field=models.ManyToManyField(related_name='applicants', through='Juniors.Interest', to='Recruiters.joblisting'),
        ),
    ]
